# Travis-CI.org configuration file

# Use Travis container-based infrastructure
sudo: False

# Language
language: python

# Python version
python:
  - 2.7

# Environment variables
env:
  - HELLO=WORLD

# Install packages in container
addons:
  apt:
    packages:
      - unixodbc-dev

# Install Python requirements before testing
install:
  - pip install -q pytest salt
  - pip install -q -r requirements.txt

# Do necessary things before testing
before_script:
  # Copy the empty secret_config.py template necessary to run app
  - cp flask_app/config/secret_config.py.template flask_app/config/secret_config.py
  # Generate secret key and initialize database
  - python setup_app.py --quiet

# Run pytest
script:
  - py.test

# Disable email notificaitons
notifications:
  email: false
